# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7124a0fe5e978c947c5884a08d22087fea688bc6a8a14baf3efa7279242dde15ba641c44a731d02589b6f8750076e4cded219e272aa5c35e04a95217d94a0616

test:
  secret_key_base: 1cc41c23fc73b6592a0ebe47271bc25417fe6347540e32d8524e086e910e70fd3f4984e5ef4a7ffbc6f8efe25de2f605716f551491ccac9995d6d71e0243d411

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
